### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by bratao** [icfly2/simstring-fast#40]
Running the example in the latest version (0.3.0) :

```
from simstring.feature_extractor.word_ngram import WordNgramFeatureExtractor
from simstring.database.dict import DictDatabase

db = DictDatabase(WordNgramFeatureExtractor(2))
db.add('You are so cool.')
```

Fails with
```
Traceback (most recent call last):
  File "C:\Users\brata\AppData\Roaming\JetBrains\PyCharmCE2023.3\scratches\scratch_31.py", line 7, in <module>
    db.add('You are so cool.')
  File "simstring\database\dict.py", line 42, in add
TypeError: str object expected; got tuple[str, str]
```

**Comment by bratao** [comment]
Seems that the code is correct. The compiled mypyc that somehow expects this function signature. Crazy!

**Comment by icfly2** [comment]
What versions of python and mypyc are you running?
